export const RADIAL_MENU_NODE_COUNT = 5;
export const RADIAL_MENU_RING_RADIUS = 102;
export const RADIAL_MENU_CORE_SIZE = 74;
export const RADIAL_MENU_ACTION_WIDTH = 76;
export const RADIAL_MENU_ACTION_HEIGHT = 40;
export const RADIAL_MENU_TOGGLE_WIDTH = 88;
export const RADIAL_MENU_TOGGLE_WIDTH_ACTIVE = 94;
export const RADIAL_MENU_TOGGLE_HEIGHT = 36;
export const RADIAL_MENU_VIEWPORT_PADDING = 24;
export const RADIAL_MENU_REVEAL_DURATION = 0.18;
export const RADIAL_MENU_STAGGER = 0.09;
export const RADIAL_MENU_CLOSE_DURATION = 0.16;
export const RADIAL_MENU_TILT_INTENSITY = 4;
export const RADIAL_MENU_PARALLAX_INTENSITY = 3.5;
export const RADIAL_MENU_NODE_START_RATIO = 0.78;
export const RADIAL_MENU_GLOW_SIZE = 184;
export const RADIAL_MENU_EASE = [0.42, 0, 0.58, 1];

export const RADIAL_MENU_FOOTPRINT_RADIUS = (
  RADIAL_MENU_RING_RADIUS
  + (Math.max(RADIAL_MENU_ACTION_WIDTH, RADIAL_MENU_TOGGLE_WIDTH_ACTIVE) / 2)
  + 18
);
