export const RADIAL_MENU_NODE_COUNT = 6;
export const RADIAL_MENU_RING_RADIUS = 108;
export const RADIAL_MENU_CORE_SIZE = 84;
export const RADIAL_MENU_NODE_SIZE = 58;
export const RADIAL_MENU_TOGGLE_WIDTH = 92;
export const RADIAL_MENU_TOGGLE_WIDTH_ACTIVE = 108;
export const RADIAL_MENU_VIEWPORT_PADDING = 28;
export const RADIAL_MENU_REVEAL_DURATION = 0.18;
export const RADIAL_MENU_STAGGER = 0.09;
export const RADIAL_MENU_CLOSE_DURATION = 0.16;
export const RADIAL_MENU_TILT_INTENSITY = 6;
export const RADIAL_MENU_PARALLAX_INTENSITY = 5;
export const RADIAL_MENU_NODE_START_RATIO = 0.78;
export const RADIAL_MENU_GLOW_SIZE = 280;
export const RADIAL_MENU_EASE = [0.42, 0, 0.58, 1];

export const RADIAL_MENU_FOOTPRINT_RADIUS = (
  RADIAL_MENU_RING_RADIUS
  + (RADIAL_MENU_NODE_SIZE / 2)
  + 24
);
