const airpasteBridge = window.airpaste ?? {};
const electronBridge = window.electronAPI ?? {};

export const desktop = {
  workspace: {
    openFolder: (...args) => airpasteBridge.openFolder?.(...args) ?? Promise.resolve(null),
    createWorkspace: (...args) => airpasteBridge.createWorkspace?.(...args) ?? Promise.resolve(null),
    loadWorkspace: (...args) => airpasteBridge.loadWorkspace?.(...args) ?? Promise.resolve(null),
    saveWorkspace: (...args) => airpasteBridge.saveWorkspace?.(...args) ?? Promise.resolve(null),
    createProject: (...args) => airpasteBridge.createProject?.(...args) ?? Promise.resolve(null),
    createSpace: (...args) => airpasteBridge.createSpace?.(...args) ?? Promise.resolve(null),
    createCanvas: (...args) => airpasteBridge.createCanvas?.(...args) ?? Promise.resolve(null),
    createPage: (...args) => airpasteBridge.createPage?.(...args) ?? Promise.resolve(null),
    listProjects: (...args) => airpasteBridge.listProjects?.(...args) ?? Promise.resolve([]),
    getProject: (...args) => airpasteBridge.getProject?.(...args) ?? Promise.resolve(null),
    listSpaces: (...args) => airpasteBridge.listSpaces?.(...args) ?? Promise.resolve([]),
    getSpace: (...args) => airpasteBridge.getSpace?.(...args) ?? Promise.resolve(null),
    listItems: (...args) => airpasteBridge.listItems?.(...args) ?? Promise.resolve([]),
    getHomeData: (...args) => airpasteBridge.getHomeData?.(...args) ?? Promise.resolve(null),
    getRecentItems: (...args) => airpasteBridge.getRecentItems?.(...args) ?? Promise.resolve([]),
    getStarredItems: (...args) => airpasteBridge.getStarredItems?.(...args) ?? Promise.resolve([]),
    getProjectsSummary: (...args) => airpasteBridge.getProjectsSummary?.(...args) ?? Promise.resolve([]),
    getProjectContents: (...args) => airpasteBridge.getProjectContents?.(...args) ?? Promise.resolve(null),
    getSpaceContents: (...args) => airpasteBridge.getSpaceContents?.(...args) ?? Promise.resolve(null),
    loadCanvas: (...args) => airpasteBridge.loadCanvas?.(...args) ?? Promise.resolve(null),
    saveCanvas: (...args) => airpasteBridge.saveCanvas?.(...args) ?? Promise.resolve(null),
    loadPage: (...args) => airpasteBridge.loadPage?.(...args) ?? Promise.resolve(null),
    savePage: (...args) => airpasteBridge.savePage?.(...args) ?? Promise.resolve(null),
    renameProject: (...args) => airpasteBridge.renameProject?.(...args) ?? Promise.resolve(null),
    renameSpace: (...args) => airpasteBridge.renameSpace?.(...args) ?? Promise.resolve(null),
    renameCanvas: (...args) => airpasteBridge.renameCanvas?.(...args) ?? Promise.resolve(null),
    renamePage: (...args) => airpasteBridge.renamePage?.(...args) ?? Promise.resolve(null),
    markItemStarred: (...args) => airpasteBridge.markItemStarred?.(...args) ?? Promise.resolve(null),
    loadUiState: (...args) => airpasteBridge.loadUiState?.(...args) ?? Promise.resolve(null),
    saveUiState: (...args) => airpasteBridge.saveUiState?.(...args) ?? Promise.resolve(null),
    deleteProject: (...args) => airpasteBridge.deleteProject?.(...args) ?? Promise.resolve({ deleted: false }),
    deleteSpace: (...args) => airpasteBridge.deleteSpace?.(...args) ?? Promise.resolve({ deleted: false }),
    deleteCanvas: (...args) => airpasteBridge.deleteCanvas?.(...args) ?? Promise.resolve({ deleted: false }),
    deletePage: (...args) => airpasteBridge.deletePage?.(...args) ?? Promise.resolve({ deleted: false }),
    fetchLinkPreview: (...args) => airpasteBridge.fetchLinkPreview?.(...args) ?? Promise.resolve({ queued: false }),
    cancelLinkPreview: (...args) => airpasteBridge.cancelLinkPreview?.(...args) ?? Promise.resolve({ cancelled: false }),
    importImageAsset: (...args) => airpasteBridge.importImageAsset?.(...args) ?? Promise.resolve(null),
    resolveAssetUrl: (...args) => airpasteBridge.resolveAssetUrl?.(...args) ?? Promise.resolve(""),
    getLastFolder: (...args) => airpasteBridge.getLastFolder?.(...args) ?? Promise.resolve(null),
    onPreviewUpdated: (listener) => airpasteBridge.onPreviewUpdated?.(listener) ?? (() => {}),
  },
  shell: {
    openExternal: (url) => airpasteBridge.openExternal?.(url) ?? Promise.resolve({ opened: false }),
  },
  window: {
    minimize: () => electronBridge.minimize?.(),
    maximize: () => electronBridge.maximize?.(),
    close: () => electronBridge.close?.(),
    usesCustomTitlebar: electronBridge.usesCustomTitlebar === true,
  },
};
